#!/usr/bin/env bash

set -euxo pipefail

# Settings
EMACS_HOME=~/.emacs.d
STRAIGHT_VERSIONS="${EMACS_HOME}/straight/versions"
FOLDERS_TO_REMOVE=(lisp snippets theme)

CLEAN="${CLEAN:-0}"
if [[ "${CLEAN}" -eq 1 ]]; then
    FOLDERS_TO_REMOVE+=(straight tree-sitter)
fi

# Purge previous configuration
if [ -d "${EMACS_HOME}" ]; then
    for i in "${FOLDERS_TO_REMOVE[@]}"; do
        rm -rf "${EMACS_HOME:?}/${i}" || true
    done

    rm "${EMACS_HOME}"/{early-init.el,init.el} || true
else
    mkdir "${EMACS_HOME}"
fi

# Install package lock
mkdir -p "${STRAIGHT_VERSIONS}"
cp package-lock.el "${STRAIGHT_VERSIONS}/default.el"

# Install new configuration
cp early-init.el init.el "${EMACS_HOME}"

for i in lisp snippets theme; do
    cp -r "${i}" "${EMACS_HOME}"
done

# Create auxiliary directories
for i in auto-save-list locks; do
    mkdir -p "${EMACS_HOME}/${i}"
done
